const majorChords = 'maj, M7, M9, 6'
const minorChords = 'm, m7, m9'
const dominantChords = 'maj, 7, 9, 13'
const fourthChords = 'maj, maj9, maj7#11'
const halfDimChords = 'm7♭5'
const ionianArray = [{note:'C',chords:majorChords},{note:'D',chords:minorChords},{note:'E',chords:minorChords},{note:'F',chords:fourthChords},{note:'G',chords:dominantChords},{note:'A',chords:minorChords},{note:'B',chords:halfDimChords}]
const dorianArray = ionianArray.splice(1,6,0).concat(ionianArray[0])
const phrygianArray = dorianArray.splice(1,6,0).concat(dorianArray[0])
const lydianArray = phrygianArray.splice(1,6,0).concat(phrygianArray[0])
const mixolydianArray = lydianArray.splice(1,6,0).concat(lydianArray[0])
const aeolianArray = mixolydianArray.splice(1,6,0).concat(mixolydianArray[0])
const locrianArray = mixolydianArray.splice(1,6,0).concat(mixolydianArray[0])
export const ionianChords = ionianArray
export const dorianChords = dorianArray
export const phrygianChords = phrygianArray
export const lydianChords = lydianArray
export const mixolydianChords = mixolydianArray
export const aeolianChords = aeolianArray
export const locrianChords = locrianArray
